### ISSUE TITLE
use i3, you macos fanboi

### ISSUE THREAD

**Issue by vitreo12** [jamesb93/hammerspoon#1]
!!!

**Comment by jamesb93** [comment]
wow!

**Comment by jamesb93** [comment]
Closing because this seems like a personal issue:

https://en.wikipedia.org/wiki/Social_issue#Personal_issues

**Comment by jamesb93** [comment]
Reopening for further discussion

**Comment by jamesb93** [comment]
This is a good first issue for your therapist.

**Comment by vitreo12** [comment]
wow, such anger

**Comment by vitreo12** [comment]
I recommend this article: https://en.wikipedia.org/wiki/Anger_management
